version: '3.9'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_DB: booking_db
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_pass
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - booking-net

  booking-service:
    build: ./booking-service
    depends_on:
      - postgres
    environment:
      POSTGRES_HOST: postgres
      POSTGRES_USER: booking_user
      POSTGRES_PASSWORD: booking_pass
      POSTGRES_DB: booking_db
    ports:
      - "8000:8000"
    networks:
      - booking-net

  user-service:
    build: ./user-service
    ports:
      - "8001:8000"
    networks:
      - booking-net

networks:
  booking-net:
    driver: bridge

volumes:
  pgdata:
