version: "3.9"

services:
  booking-service:
    build: ./booking-service
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  user-service:
    build: ./user-service
    ports:
      - "8003:8000"

  payment-service:
    build: ./payment-service
    ports:
      - "8001:8001"

  notification-service:
    build: ./notification-service
    ports:
      - "8002:8002"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: booking
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
